#!/usr/bin/env python3
"""Merge non-overlapping iNaturalist metadata chunks before global queue building.

Each chunk comes from `04_collect_inat_cirsium_metadata.py` run with a distinct
`--start-obs-id` and a bounded `--max-observations`. This utility validates
schema, removes accidental duplicate photos, preserves every source-chunk
identifier, and produces a single global `photo_metadata_merged.csv` suitable
for `05_build_image_screening_queue.py`.

Example
-------
python ch1_global/v2/10_merge_metadata_chunks.py \
  --input-dir artifacts/metadata_chunks \
  --out-dir merged_metadata
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge Chapter 1 iNaturalist metadata chunks.")
    parser.add_argument("--input-dir", required=True, help="Directory containing downloaded chunk artifact folders.")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--pattern", default="**/photo_metadata.csv", help="Glob relative to input directory.")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir)
    paths = sorted(input_dir.glob(args.pattern))
    if not paths:
        raise FileNotFoundError(f"No metadata files matching {args.pattern!r} below {input_dir}")

    tables: list[pd.DataFrame] = []
    expected_columns: list[str] | None = None
    source_rows: list[dict[str, object]] = []
    for path in paths:
        table = pd.read_csv(path, dtype=str, keep_default_na=False)
        if expected_columns is None:
            expected_columns = list(table.columns)
        elif list(table.columns) != expected_columns:
            raise ValueError(f"Schema mismatch in {path}; merge only chunks generated by the same collector schema.")
        required = {"obs_id", "photo_id", "taxon_name", "source_file_stem"}
        missing = required.difference(table.columns)
        if missing:
            raise ValueError(f"{path} missing required columns: {sorted(missing)}")
        table["metadata_chunk_source"] = str(path.parent.relative_to(input_dir))
        tables.append(table)
        source_rows.append({
            "metadata_path": str(path.relative_to(input_dir)),
            "sha256": sha256(path),
            "n_rows": int(len(table)),
            "n_observations": int(table["obs_id"].nunique()),
            "n_photos": int(table["photo_id"].nunique()),
        })

    merged = pd.concat(tables, ignore_index=True)
    before = len(merged)
    merged = merged.drop_duplicates(subset=["photo_id"], keep="first").copy()
    merged = merged.sort_values(["obs_id", "photo_id"], key=lambda col: pd.to_numeric(col, errors="coerce"), kind="stable").reset_index(drop=True)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    merged_path = out_dir / "photo_metadata_merged.csv"
    merged.to_csv(merged_path, index=False, encoding="utf-8-sig")
    pd.DataFrame(source_rows).to_csv(out_dir / "metadata_chunk_sources.csv", index=False, encoding="utf-8-sig")
    provenance = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "input_dir": str(input_dir.resolve()),
        "n_input_chunks": len(paths),
        "n_rows_before_photo_deduplication": int(before),
        "n_rows_after_photo_deduplication": int(len(merged)),
        "n_duplicate_photo_rows_removed": int(before - len(merged)),
        "n_observations": int(merged["obs_id"].nunique()),
        "n_species": int(merged.loc[merged.get("taxon_rank", "").astype(str).eq("species"), "taxon_name"].nunique()) if "taxon_rank" in merged.columns else None,
        "merged_file": merged_path.name,
    }
    (out_dir / "merge_provenance.json").write_text(json.dumps(provenance, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(provenance, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
